--- # Setup a New Host
- hosts: localhost
  become: true
  pre_tasks:
  - name: updateRepos
    yum: update_cache=yes name=* state=latest
    changed_when: false
  vars_prompt:
  - name: username
    prompt: What is username?
    default: user
  vars:
    dest: /home/"{{username}}"
    result: destresult
    debug: destresult
  tasks:
  - name: install packages
    yum: name={{ item }} state=latest
    with_items:
      - htop
      - git
      - vim
      - ruby
  - name: Install bundler
    gem:
      name: bundler
      state: latest
      user_install: no
  - name: CreateUser
    user:
      name: '{{ username }}'
      state: present
      generate_ssh_key: yes
  - name: Copy-vimrc
    copy: src=files/.vimrc dest="/home/{{username}}/.vimrc"
  - name: Copy-vimrc
    copy: src=files/.bashrc dest="/home/{{username}}/.bashrc"
