--- # Setup a New Host
- hosts: localhost
  become: true
  pre_tasks:
  - name: updateRepos
    yum: update_cache=yes name=* state=latest
    changed_when: false
  vars:
  - name: username
    prompt: What is username?
    default: user
  tasks:
  - name: install packages
    yum: name={{ item }} state=latest
    with_items:
      - htop
      - git
      - vim
  - name: Copy-vimrc
    copy:
      src: files/.vimrc
      dest: /home/"{{username}}"/.vimrc
  - name: CreateUser
    user:
      name: "{{ username }}"
      state: present

